### ISSUE TITLE
Oneplus12 oxygen14 not work

### ISSUE THREAD

**Issue by seraph758** [rifsxd/process-hook#1]
![Screenshot_2024-09-23-19-22-00-00_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/e35f8d2e-953b-42d2-a3be-a3508e9e99fc)
Not work

**Comment by seraph758** [comment]
![Uploading Screenshot_2024-09-23-19-22-51-71_084ab3bc34f7aa7ccff83653f52abafc.jpg…]()

**Comment by rifsxd** [comment]
Can you download and install the apk again and install device info from play store and force stop it in lsposed and show me device section screen shot?

**Comment by seraph758** [comment]
Screenshots about what

**Comment by seraph758** [comment]
![Screenshot_2024-09-24-11-26-10-91_dac78dbb8b9d35e2ecbeaf4ec6ecff5b](https://github.com/user-attachments/assets/14d164a5-4db4-4862-952b-d1826e0d6490)
![Screenshot_2024-09-24-11-24-03-11_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/6a69e487-db89-4696-82bf-e76570c9502f)

**Comment by seraph758** [comment]
[Uploading LSPosed_2024-09-24T11_43_21.170630.zip…]()

**Comment by rifsxd** [comment]
> Screenshots about what

Device Info app from play store which is for debugging to check if it's working or not

**Comment by rifsxd** [comment]
> Uploading LSPosed_2024-09-24T11_43_21.170630.zip…

Upload the logs properly

**Comment by rifsxd** [comment]
https://play.google.com/store/apps/details?id=com.ytheekshana.deviceinfo

Install this and force stop in lsposed and show me the device section if props are being injected or not plus lsposed logs

**Comment by rifsxd** [comment]
![Screenshot_20240924-102614](https://github.com/user-attachments/assets/49f95b95-5ab7-46ee-8ca4-5c88fe7bd7e2)
This

**Comment by seraph758** [comment]
[LSPosed_2024-09-24T11_43_21.170630.zip](https://github.com/user-attachments/files/17108221/LSPosed_2024-09-24T11_43_21.170630.zip)

**Comment by seraph758** [comment]
![Screenshot_2024-09-24-13-02-13-24_e4fefa24eecccd406e1682398cde070b](https://github.com/user-attachments/assets/10cc9cb9-fbff-40cc-8c8b-41a87daead75)

**Comment by rifsxd** [comment]
Okay the module is not working for you, did you force stop device info then ran it? Just give me lsposed logs to identify the issue

**Comment by seraph758** [comment]
> 好的，该模块对您不起作用，您是否强制停止设备信息然后运行它？

强制停止过，手机自动重启过。游戏也重新下载试过
