### ISSUE TITLE
Battlegrounds mobile India 

### ISSUE THREAD

**Issue by RyomenRR** [rifsxd/process-hook#10]
BGMI 120fps is not unlocking other apps are fine 😐

**Comment by RyomenRR** [comment]
com.pubg.imobile 
Battlegrounds mobile India 
They introduced 120 in recent update and only specific devices are supported

**Comment by rifsxd** [comment]
check https://github.com/rifsxd/process-hook/blob/main/app/src/main/java/com/rifsxd/processhook/deviceProperties.java#L204 

BGMI is spoofed as Black Shark which is also configured for 120hz at https://github.com/rifsxd/process-hook/blob/main/app/src/main/java/com/rifsxd/processhook/deviceProperties.java#L78

if it still doesn't work then idk what BGMI is doing

**Comment by RyomenRR** [comment]
Can you change it to Rog or Samsung? cause there's no official supporting device list but I know this 2 device has support (checked from YouTube) .

**Comment by rifsxd** [comment]
> Can you change it to Rog or Samsung? cause there's no official supporting device list but I know this 2 device has support (checked from YouTube) .

Sure

**Comment by rifsxd** [comment]
Changed it to Galaxy S24 Ultra, you can check the latest GitHub actions CI builds to check if it   works or not.

**Comment by RyomenRR** [comment]
Yayyy 

![Screenshot_2024-11-26-20-40-39-226_com pubg imobile](https://github.com/user-attachments/assets/cb23dba0-7ec0-4d5a-b83a-d9428bed23ea)
