### ISSUE TITLE
I installed modded blitz apk

### ISSUE THREAD

**Issue by DenBru456** [rifsxd/process-hook#3]
Your module doesn't work on that

**Comment by rifsxd** [comment]
I should work as long as the app package is the same

**Comment by rifsxd** [comment]
Fixed and working with release 1.2.0 with commits

[Added wotblitz to the scope](https://github.com/rifsxd/process-hook/commit/16a626d62db3267b25e0db8f908abdf7cafba5bb)

[fixed invalid model spec and improved product spec and added Mi 14 Pro device to the spoofing model](https://github.com/rifsxd/process-hook/commit/c994bcc3c492434f5b59974afa01966ba5ea4617)
