### ISSUE TITLE
30 fps on Wild Rift

### ISSUE THREAD

**Issue by astrophilehuwan** [rifsxd/process-hook#4]
On versions 1.1.0 and 1.2.0, whenever I play Wild Rift, the FPS would stay at 30 FPS even though I set it to 60 FPS. The only way to play the game to 60 FPS is if you change the setting to 90 FPS which is weird. On 1.0.0, it doesn't have this issue.

**Comment by rifsxd** [comment]
which variant of Wild Rift?

**Comment by rifsxd** [comment]
[app-release.zip](https://github.com/user-attachments/files/17173478/app-release.zip)

can you try installing this test version and see if it works as intended?

**Comment by rifsxd** [comment]
[Uploading app-debug.zip…]()

Can you try installing this test build and see if it works as intended?

**Comment by rifsxd** [comment]
[app-debug.zip](https://github.com/user-attachments/files/17173482/app-debug.zip)

Can you try installing this test build and see if it works as intended?

**Comment by astrophilehuwan** [comment]
Heyyy, I'm really sorry. It looks like the issue is on my end. I'm on Samsung, and it is due to the Thermal Guardian. But I'm not sure why this happened since it didn't happen on version 1. But everything's fixed now and I've unticked all of the options on Additional settings.
![Screenshot_20240929_091803_Thermal Guardian](https://github.com/user-attachments/assets/37d7b975-6584-465e-be65-ea2459f8141b)

**Comment by rifsxd** [comment]
It's okay lol I just couldn't figure out what the hell was wrong since I debugged the hell out of it and still couldn't reproduce the issue
