### ISSUE TITLE
wrong versionCode

### ISSUE THREAD

**Issue by IzzySoft** [rifsxd/process-hook#5]
Looks like you forgot to [increase `versionCode`](https://github.com/rifsxd/process-hook/blob/main/app/build.gradle#L13) since you released the first version – it's still saying `1`, i.e. the very first version. As Android uses that internally to tell versions apart, e.g. 1.3.0 is **not** seen as an update to 1.2.0 (or any other previous version) – but Android thinks it's already installed.

Can you please take care to always increase this with new releases? Thanks in advance!

**Comment by rifsxd** [comment]
Says who?
![Screenshot_20241021-021902](https://github.com/user-attachments/assets/4c26a21f-a135-4e4d-a78d-11a0ff182eca)

**Comment by rifsxd** [comment]
Guess I forgot about that

**Comment by rifsxd** [comment]
[fixed versionCode](https://github.com/rifsxd/process-hook/commit/6f1ea85d54815cb7349a0f76937d6f2d751acd74) fixed

**Comment by IzzySoft** [comment]
Thanks! Will become available [in the IzzyOnDroid repo](https://apt.izzysoft.de/packages/com.rifsxd.processhook) with the next sync around 6 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme if you wish :smiley:

(for updates to work there, please remember increasing `versionCode` with each future release :wink:)
