### ISSUE TITLE
Game support request: Fortnite Mobile. Doesn't work for Fortnite Mobile

### ISSUE THREAD

**Issue by blast34** [rifsxd/process-hook#7]
hii I've tried this app with fn mobile it struggles to get hardly 60fps tho my phone has 90fps display.
I haven't tried this app on other games tho...
I installed the game from official Epic Games store.
can you maybe add Fortnite Mobile game to support process hook plss...

**Comment by rifsxd** [comment]
Send me the package Id of the Fortnite apk

**Comment by blast34** [comment]
> Send me the package Id of the Fortnite apk

idk whether this is correct or not but i got this as package id:

Fortnite
com.epicgames.fortnite
com.epicgames.unreal.SplashActivity

**Comment by blast34** [comment]
i'd appreciate if you could help, thanks

**Comment by rifsxd** [comment]
Fortnite package is already set to spoof as 120hz since you are not get even 60fps indicates your device is not powerful enough to go above 60fps
