### ISSUE TITLE
can unlock graphics?

### ISSUE THREAD

**Issue by alvlp-code** [rifsxd/process-hook#8]
i have try to force close pubg and graphics still not unlocked

**Comment by RyomenRR** [comment]
Try restarting system UI or phone

**Comment by rifsxd** [comment]
> i have try to force close pubg and graphics still not unlocked

Which PUBG? Give me the package id

**Comment by alvlp-xyz** [comment]
> > i have try to force close pubg and graphics still not unlocked
> 
> Which PUBG? Give me the package id

com.tencent.ig

**Comment by rifsxd** [comment]
Can you go download any of the debug apps listed in the readme and testing if it's spoofing correctly

**Comment by Ahmed768047** [comment]
Hello, when charging a PUBG account via the Huawei application, there is a chargeable ban for some workers. Is it possible to bypass this ban?

**Comment by rifsxd** [comment]
Currently no
