### ISSUE TITLE
Customisable

### ISSUE THREAD

**Issue by RyomenRR** [rifsxd/process-hook#9]
You listed 8 devices which can we spoof buy my phone select default S24U and I want to change it there's no option there or guide available

**Comment by rifsxd** [comment]
The spoofing is done statically and not interchangeable from the app yet, if you want to change device you have to change it from the source code and build app, I will add an option to able to change within the app

**Comment by RyomenRR** [comment]
Well I don't have any knowledge about that so I'll wait problem is S24U international one has no 120 fps support in BATTLEGROUNDS MOBILE INDIA that's what happened to me every other game works fine
